name: Deploy Flask App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug GitHub Context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"

      - name: Debug OIDC Claims
        run: |
          TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" \
          -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" | jq -r '.value')

          echo "$TOKEN" | cut -d "." -f2 | base64 -d | jq

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::768396678386:role/GitHubActions-AppDeploy-Role
          aws-region: us-east-1
          role-session-name: GitHubActionsDebug
          mask-aws-account-id: false

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      - name: Encode application files
        run: |
          APP=$(base64 -w 0 app.py)
          REQ=$(base64 -w 0 requirements.txt)

          echo "APP=$APP" >> $GITHUB_ENV
          echo "REQ=$REQ" >> $GITHUB_ENV

      - name: Deploy to App ASG
        run: |
          aws ssm send-command \
            --targets "Key=tag:aws:autoscaling:groupName,Values=asg-app-prod" \
            --document-name "AWS-RunShellScript" \
            --parameters commands="[
              'dnf install python3-pip -y',
              'mkdir -p /opt/app',
              'echo $REQ | base64 -d > /opt/app/requirements.txt',
              'pip3 install -r /opt/app/requirements.txt',
              'echo $APP | base64 -d > /opt/app/app.py',
              'systemctl restart app'
            ]"